# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(default=1, max_length=255, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
